FROM golang as builder

WORKDIR /usr/src/app

# pre-copy/cache go.mod for pre-downloading dependencies and only redownloading them in subsequent builds if they change
COPY go.mod ./
RUN go mod download && go mod verify

COPY . .
RUN go build -v -o /usr/local/bin/meu-app-desafio ./...

FROM scratch
COPY --from=builder /usr/local/bin/meu-app-desafio ./meu-app-desafio
ENTRYPOINT ["./meu-app-desafio"]


